package lightengine.tasks;

public enum Event {
  KEY_PRESSED,
  KEY_RELEASED,
  KEY_TYPED,
  MOUSE_PRESSED,
  MOUSE_RELEASED,
  MOUSE_MOVED,
  MOUSE_DRAGGED,
  MOUSE_WHEEL,
  NEW_FRAME,
  WINDOW_RESIZED,
  WINDOW_CLOSING,
  WINDOW_CLOSED,
  WINDOW_GAINED_FOCUS,
  WINDOW_LOST_FOCUS,
  WINDOW_ICONIFIED,
  WINDOW_DEICONIFIED,
}